### ISSUE TITLE
compiling log.cc on centos

### ISSUE THREAD

**Issue by djzort** [SolveMedia/ginsing#5]
i needed to add  #include <arpa/inet.h> to log.cc for it to compile on centos6

before adding it i got the error 

g++ -g -march=opteron -mtune=opteron -m64 -O3 -ffast-math -pthreads -I`pwd`/../inc -I/usr/local/m64/include -DMYNAME=\"ginsing\"   -c -o log.o log.cc
g++: unrecognized option '-pthreads'
log.cc: In function 'void out_ipv6(FILE_, uint16_t_)':
log.cc:38: error: 'htons' was not declared in this scope
log.cc: In function 'void log_request(NTD_)':
log.cc:54: error: 'sockaddr_in' was not declared in this scope
log.cc:54: error: 'si' was not declared in this scope
log.cc:55: error: 'sockaddr_in6' was not declared in this scope
log.cc:55: error: 'ss' was not declared in this scope
log.cc:78: error: expected primary-expression before ')' token
log.cc:78: error: expected ';' before 'ntd'
log.cc:82: error: expected primary-expression before ')' token
log.cc:82: error: expected ';' before 'ntd'
make: *_\* [log.o] Error 1

**Comment by jaw0** [comment]
added include
